/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrivacyPool,
  IPrivacyPoolInterface,
} from "../../../contracts/PrivacyRouter.sol/IPrivacyPool";

const _abi = [
  {
    inputs: [],
    name: "denomination",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "commitment",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPrivacyPool__factory {
  static readonly abi = _abi;
  static createInterface(): IPrivacyPoolInterface {
    return new Interface(_abi) as IPrivacyPoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPrivacyPool {
    return new Contract(address, _abi, runner) as unknown as IPrivacyPool;
  }
}
