/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { MockHasher, MockHasherInterface } from "../MockHasher";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "inputs",
        type: "uint256[2]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061019e806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806329a5f2f614610030575b600080fd5b61004361003e3660046100b8565b610055565b60405190815260200160405180910390f35b80516020808301516040805180840194909452838101919091528051808403820181526060909301905281519101206000906100b2907f30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f000000190610146565b92915050565b6000604082840312156100ca57600080fd5b82601f8301126100d957600080fd5b6040516040810181811067ffffffffffffffff8211171561010a57634e487b7160e01b600052604160045260246000fd5b806040525080604084018581111561012157600080fd5b845b8181101561013b578035835260209283019201610123565b509195945050505050565b60008261016357634e487b7160e01b600052601260045260246000fd5b50069056fea26469706673582212207dacf7bcff2c93bc5eb38ef9ae2d8abddaf19bec9ea17e81b22665f8e5862a6264736f6c63430008180033";

type MockHasherConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockHasherConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockHasher__factory extends ContractFactory {
  constructor(...args: MockHasherConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockHasher & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockHasher__factory {
    return super.connect(runner) as MockHasher__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockHasherInterface {
    return new Interface(_abi) as MockHasherInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockHasher {
    return new Contract(address, _abi, runner) as unknown as MockHasher;
  }
}
