/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PrivacyRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositVariable"
      | "getPool"
      | "getPoolCount"
      | "getRegisteredDenominations"
      | "owner"
      | "pools"
      | "registerPool"
      | "registeredDenominations"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PoolRegistered" | "VariableDeposit"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositVariable",
    values: [BigNumberish[], BigNumberish[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredDenominations",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pools", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "registerPool",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredDenominations",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositVariable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredDenominations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredDenominations",
    data: BytesLike
  ): Result;
}

export namespace PoolRegisteredEvent {
  export type InputTuple = [
    denomination: BigNumberish,
    poolAddress: AddressLike
  ];
  export type OutputTuple = [denomination: bigint, poolAddress: string];
  export interface OutputObject {
    denomination: bigint;
    poolAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VariableDepositEvent {
  export type InputTuple = [
    sender: AddressLike,
    totalAmount: BigNumberish,
    fragments: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    totalAmount: bigint,
    fragments: bigint
  ];
  export interface OutputObject {
    sender: string;
    totalAmount: bigint;
    fragments: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivacyRouter extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyRouter;
  waitForDeployment(): Promise<this>;

  interface: PrivacyRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositVariable: TypedContractMethod<
    [
      _commitments: BigNumberish[],
      _denominations: BigNumberish[],
      _token: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getPool: TypedContractMethod<[_denomination: BigNumberish], [string], "view">;

  getPoolCount: TypedContractMethod<[], [bigint], "view">;

  getRegisteredDenominations: TypedContractMethod<[], [bigint[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  registerPool: TypedContractMethod<
    [_denomination: BigNumberish, _poolAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  registeredDenominations: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositVariable"
  ): TypedContractMethod<
    [
      _commitments: BigNumberish[],
      _denominations: BigNumberish[],
      _token: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<[_denomination: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRegisteredDenominations"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerPool"
  ): TypedContractMethod<
    [_denomination: BigNumberish, _poolAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredDenominations"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "PoolRegistered"
  ): TypedContractEvent<
    PoolRegisteredEvent.InputTuple,
    PoolRegisteredEvent.OutputTuple,
    PoolRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VariableDeposit"
  ): TypedContractEvent<
    VariableDepositEvent.InputTuple,
    VariableDepositEvent.OutputTuple,
    VariableDepositEvent.OutputObject
  >;

  filters: {
    "PoolRegistered(uint256,address)": TypedContractEvent<
      PoolRegisteredEvent.InputTuple,
      PoolRegisteredEvent.OutputTuple,
      PoolRegisteredEvent.OutputObject
    >;
    PoolRegistered: TypedContractEvent<
      PoolRegisteredEvent.InputTuple,
      PoolRegisteredEvent.OutputTuple,
      PoolRegisteredEvent.OutputObject
    >;

    "VariableDeposit(address,uint256,uint256)": TypedContractEvent<
      VariableDepositEvent.InputTuple,
      VariableDepositEvent.OutputTuple,
      VariableDepositEvent.OutputObject
    >;
    VariableDeposit: TypedContractEvent<
      VariableDepositEvent.InputTuple,
      VariableDepositEvent.OutputTuple,
      VariableDepositEvent.OutputObject
    >;
  };
}
